ALTER TABLE "LearningGoal"
ADD COLUMN "newWordsPerDay" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "vocabularyPaceSetAt" TIMESTAMP(3);

ALTER TABLE "DailyAssignment"
ADD COLUMN "newWordsLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "vocabularyTerms" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
