ALTER TABLE "LearningGoal"
ADD COLUMN "endingPhasePosition" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN "targetTrack" TEXT NOT NULL DEFAULT 'MASTERY_800',
ADD COLUMN "goalAchievedAt" TIMESTAMP(3),
ADD COLUMN "lastCheckpointAt" TIMESTAMP(3);
